export type {
  Masterclass,
  MasterclassCard,
  MasterclassContentItem,
  MasterclassExpert,
  MasterclassExpertSocial,
  MasterclassFormatItem,
  MasterclassForWhoItem,
  MasterclassProblemItem,
  MasterclassSection,
  MasterclassSectionContent,
  MasterclassSectionExpert,
  MasterclassSectionFinalCta,
  MasterclassSectionFormat,
  MasterclassSectionForWho,
  MasterclassSectionHero,
  MasterclassSectionProblem,
  MasterclassSectionSettings,
  MasterclassSectionTransformation,
  MasterclassSeo,
  MasterclassStatus,
  MasterclassTransformationItem,
} from '@ez/web/types/masterclass'
