export type {
  Webinar,
  WebinarCard,
  WebinarContentItem,
  WebinarExpert,
  WebinarExpertSocial,
  WebinarFormatItem,
  WebinarForWhoItem,
  WebinarProblemItem,
  WebinarSection,
  WebinarSectionContent,
  WebinarSectionExpert,
  WebinarSectionFinalCta,
  WebinarSectionFormat,
  WebinarSectionForWho,
  WebinarSectionHero,
  WebinarSectionProblem,
  WebinarSectionSettings,
  WebinarSectionTransformation,
  WebinarSeo,
  WebinarStatus,
  WebinarTransformationItem,
} from '@ez/web/types/webinar'
