// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "Instituto EZ"
  },
  "Global": {
    "copyright": "Todos os direitos reservados."
  },
  "DialogContact": {
    "title": "How can we help you?",
    "emailNotConfigured": "Target email is not configured.",
    "sendEmailError": "Unable to send message",
    "sendEmailSuccess": "Message sent successfully",
    "isRequired": "is required",
    "cancelButton": "Close",
    "sendButton": "Send Message",
    "loadingButton": "Sending message..."
  },
  "LandingPage": {
    "title": "Solicitar Diagnóstico",
    "sendButton": "Solicitar",
    "loadingButton": "Solicitando diagnóstico..."
  },
  "LandingPageHome": {
    "expOfYears": "Years of Experience",
    "scienceBased": "Science Based",
    "metricsPrecision": "Precisão nas Métricas",
    "safeDecision": "Tomada de Decisão Segura"
  },
  "Ebooks": {
    "backButton": "Back to Catalog",
    "reserveYourEbook": "Get your eBook now",
    "guaranteeSeals": "Guarantee Seals",
    "virtualEbook": "Browse through and discover the Ebook inside",
    "aboutAuthor": "About the Author",
    "aboutAuthors": "About the Authors",
    "frequentlyQuestions": "Frequently Asked Questions",
    "onlyText": "Only",
    "testimonial": "Testimonials"
  },
  "Languages": {
    "placeholder": "Language",
    "pt": "Portuguese",
    "en": "English",
    "es": "Spanish"
  }
};
export default messages;