// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "Instituto EZ"
  },
  "DialogContact": {
    "title": "How can we help you?"
  },
  "Ebooks": {
    "backButton": "Back to Catalog",
    "downloadButton": "Download Now!"
  }
};
export default messages;