// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "Instituto EZ"
  },
  "DialogContact": {
    "title": "How can we help you?"
  },
  "Ebooks": {
    "backButton": "Back to Catalog",
    "reserveYourEbook": "Get your eBook now",
    "guaranteeSeals": "Guarantee Seals",
    "virtualEbook": "Browse through and discover the Ebook inside",
    "aboutAuthor": "About the Author",
    "aboutAuthors": "About the Authors",
    "frequentlyQuestions": "Frequently Asked Questions",
    "onlyText": "Only",
    "testimonial": "Testimonials"
  },
  "Languages": {
    "placeholder": "Language",
    "pt": "Portuguese",
    "en": "English",
    "es": "Spanish"
  }
};
export default messages;