// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "Instituto EZ"
  },
  "DialogContact": {
    "title": "¿Cómo podemos ayudarle?",
    "emailNotConfigured": "El correo electrónico de destino no está configurado.",
    "sendEmailError": "No se puede enviar el mensaje",
    "sendEmailSuccess": "Mensaje enviado correctamente",
    "isRequired": "es obligatorio",
    "cancelButton": "Cerrar",
    "sendButton": "Enviar mensaje",
    "loadingButton": "Enviando mensaje..."
  },
  "LandingPage": {
    "title": "Solicitar Diagnóstico",
    "sendButton": "Solicitar",
    "loadingButton": "Solicitando diagnóstico..."
  },
  "LandingPageHome": {
    "expOfYears": "Anos de Experiência",
    "scienceBased": "Baseado em Ciência",
    "metricsPrecision": "Precisão nas Métricas",
    "safeDecision": "Tomada de Decisão Segura"
  },
  "Ebooks": {
    "backButton": "Volver al catálogo",
    "reserveYourEbook": "Consigue tu eBook ahora",
    "guaranteeSeals": "Sellos de garantía",
    "virtualEbook": "Navega y descubre el Ebook que hay dentro",
    "aboutAuthor": "Acerca del Autor",
    "aboutAuthors": "Acerca del Autores",
    "frequentlyQuestions": "Preguntas Frecuentes",
    "onlyText": "Apenas",
    "testimonial": "Testimonios"
  },
  "Languages": {
    "placeholder": "Idioma",
    "pt": "Portugués",
    "en": "Inglés",
    "es": "Español"
  }
};
export default messages;