// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "DialogContact": {
    "title": "¿Cómo podemos ayudarle?",
    "emailNotConfigured": "El correo electrónico de destino no está configurado.",
    "sendEmailError": "No se puede enviar el mensaje",
    "sendEmailSuccess": "Mensaje enviado correctamente",
    "isRequired": "es obligatorio",
    "nameRequired": "El nombre es obligatorio",
    "emailRequired": "El correo electrónico es obligatorio",
    "emailInvalid": "Introduce un correo electrónico válido",
    "phoneRequired": "El teléfono es obligatorio",
    "subjectRequired": "El asunto es obligatorio",
    "messageRequired": "El mensaje es obligatorio",
    "nameLabel": "Nombre",
    "emailLabel": "Correo electrónico",
    "phoneLabel": "Teléfono",
    "subjectLabel": "Asunto",
    "messageLabel": "Mensaje",
    "loadingAria": "Cargando formulario",
    "cancelButton": "Cerrar",
    "sendButton": "Enviar mensaje",
    "loadingButton": "Enviando mensaje..."
  },
  "EmailTemplate": {
    "preview": "Nuevo contacto desde el formulario",
    "title": "Nuevo contacto recibido",
    "subjectLabel": "Asunto:",
    "nameLabel": "Nombre:",
    "emailLabel": "Correo electrónico:",
    "phoneLabel": "Teléfono:",
    "fromLabel": "Contacto - Sitio"
  }
};
export default messages;