// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "Instituto EZ"
  },
  "DialogContact": {
    "title": "Como podemos te ajudar?",
    "emailNotConfigured": "Email de destino não está configurado.",
    "sendEmailError": "Não foi possível enviar a mensagem",
    "sendEmailSuccess": "Mensagem enviada com sucesso",
    "isRequired": "é obrigatório",
    "cancelButton": "Fechar",
    "sendButton": "Enviar Mensagem",
    "loadingButton": "Enviando mensagem..."
  },
  "LandingPageMathematizer": {
    "title": "Solicitar Diagnóstico",
    "sendButton": "Solicitar",
    "loadingButton": "Solicitando diagnóstico..."
  },
  "Ebooks": {
    "backButton": "Voltar para o Catálogo",
    "reserveYourEbook": "Garanta já seu eBook",
    "guaranteeSeals": "Selos de Garantia",
    "virtualEbook": "Folheie e conheça o Ebook por dentro",
    "aboutAuthor": "Sobre o Autor",
    "aboutAuthors": "Sobre os Autores",
    "frequentlyQuestions": "Perguntas Frequentes",
    "onlyText": "Apenas",
    "testimonial": "Depoimentos"
  },
  "Languages": {
    "placeholder": "Idioma",
    "pt": "Português",
    "en": "Inglês",
    "es": "Espanhol"
  }
};
export default messages;