// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "Instituto EZ"
  },
  "DialogContact": {
    "title": "Como podemos te ajudar?"
  },
  "Ebooks": {
    "backButton": "Voltar para o Catálogo",
    "downloadButton": "Baixar Agora!"
  }
};
export default messages;